FROM centos:7@sha256:73f11afcbb50d8bc70eab9f0850b3fa30e61a419bc48cf426e63527d14a8373b

ENV PLATFORM="linux/arm64"

RUN mkdir -p /opt/python

COPY tools/manylinux-bootstrap /opt/python/manylinux-bootstrap

RUN /opt/python/manylinux-bootstrap

COPY tools/manylinux-2014 /usr/local/bin/manylinux-2014
