FROM centos:7@sha256:dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f

ENV PLATFORM="linux/amd64"

RUN mkdir -p /opt/python

COPY tools/manylinux-bootstrap /opt/python/manylinux-bootstrap

RUN /opt/python/manylinux-bootstrap

COPY tools/manylinux-2014 /usr/local/bin/manylinux-2014
